const nodemailer = require("nodemailer");

module.exports = async function handler(req, res) {
  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  try {
    const {
      studentName,
      score,
      totalQuestions,
      percentage,
      strengths,
      needsPractice,
      summary
    } = req.body;

    const transporter = nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: process.env.GMAIL_USER,
        pass: process.env.GMAIL_APP_PASSWORD
      }
    });

    const recipients = [
      process.env.PARENT_EMAIL_1,
      process.env.PARENT_EMAIL_2
    ].filter(Boolean);

    await transporter.sendMail({
      from: `"Math Accelerator" <${process.env.GMAIL_USER}>`,
      to: recipients.join(","),
      subject: `Math Practice Report${studentName ? ` — ${studentName}` : ""}`,
      text: `
Math Practice Report

Student: ${studentName || "Student"}

Score: ${score ?? "—"} / ${totalQuestions ?? "—"}
Percentage: ${percentage ?? "—"}%

STRENGTHS
${strengths || "No strengths recorded."}

NEEDS PRACTICE
${needsPractice || "No areas recorded."}

SESSION SUMMARY
${summary || "No summary available."}

This report was automatically generated by Math Accelerator.
      `.trim()
    });

    return res.status(200).json({
      success: true,
      message: "Parent report sent."
    });

  } catch (error) {
    console.error("Email error:", error);

    return res.status(500).json({
      success: false,
      error: "Unable to send parent report."
    });
  }
};
